default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: appointment_development

test:
  <<: *default
  database: appointment_test

production:
  <<: *default
  database: appointment_production
  username: <%= ENV['AWS_POSTGRES'] %>
  password: <%= ENV['AWS_POSTGRES_PASSWORD'] %>
